### ISSUE TITLE
Variable not on cuda

### ISSUE THREAD

**Issue by yummyJade** [jiangyzy/GOAE#1]
Thank you for your great job!
I notice there may be a mistake in inference code 

![image](https://github.com/jiangyzy/GOAE/assets/32930873/111132e9-4c33-4ba1-a6a7-425f029efb43)

```
logit_scale = torch.clamp(self.logit_scale, max=torch.log(torch.tensor(1. / 0.01))).exp()
```

it can fixed by
```
logit_scale = torch.clamp(self.logit_scale, max=torch.log(torch.tensor(1. / 0.01)).to('cuda')).exp()
```

**Comment by jiangyzy** [comment]
> Thank you for your great job! I notice there may be a mistake in inference code
> 
> ![image](https://user-images.githubusercontent.com/32930873/258585784-111132e9-4c33-4ba1-a6a7-425f029efb43.png)
> 
> ```
> logit_scale = torch.clamp(self.logit_scale, max=torch.log(torch.tensor(1. / 0.01))).exp()
> ```
> 
> it can fixed by
> 
> ```
> logit_scale = torch.clamp(self.logit_scale, max=torch.log(torch.tensor(1. / 0.01)).to('cuda')).exp()
> ```

Thanks for your criticism, original code works well on torch==1.11.0, the fixed one is more flexible.
