### ISSUE TITLE
How to get rendered depth map?

### ISSUE THREAD

**Issue by LPHFAQ** [jiangyzy/GOAE#11]
I found that depth maps can be accessed in your paper just as the following figure:
![image](https://github.com/jiangyzy/GOAE/assets/57347617/3b952a97-c7ee-4654-8a46-80752a8b3dd0)
And I also tried to fetch the rendered depth map by add some codes:
![Snipaste_2023-12-21_15-57-22](https://github.com/jiangyzy/GOAE/assets/57347617/099772fc-f387-478f-957c-a5a2f8fcc566)
But the fetched depth map is empty ( all pixels are white) as the following figue:
![Snipaste_2023-12-21_15-58-52](https://github.com/jiangyzy/GOAE/assets/57347617/7ae94cdf-a819-4a9c-a8a7-394b80349a0d)
So would you share your method of fetching the depth maps as shown in the first figure of this issue? Or is there something wrong with my method of fetching depth map?Thx

**Comment by jiangyzy** [comment]
You may need to norm the depth map to range [0,1] when saving it.

**Comment by LPHFAQ** [comment]
你好，你发送的邮件我已受到，我会尽快回复。

**Comment by LPHFAQ** [comment]
> You may need to norm the depth map to range [0,1] when saving it.
Like this? I tried this code but the output depth maps are still empty.
![image](https://github.com/jiangyzy/GOAE/assets/57347617/7bb197e3-d135-4985-a40c-5d061dd663c4)
![image](https://github.com/jiangyzy/GOAE/assets/57347617/477a2382-0201-4d8c-8610-5379f427cf5f)

**Comment by jiangyzy** [comment]
depth = (depth - depth.min()) / (depth.max() - depth.min())

**Comment by LPHFAQ** [comment]
> depth = (depth - depth.min()) / (depth.max() - depth.min())
Got it! Thank u~
