### ISSUE TITLE
resolution question

### ISSUE THREAD

**Issue by johnren-code** [jiangyzy/GOAE#15]
`dataset_kwargs = dnnlib.EasyDict(class_name='training.dataset_face.CameraLabeledDataset', path=data_path, use_labels=True, max_size=None, xflip=False,resolution=256, use_512 = True)`  why the resolution is set to 256 ?

**Comment by jiangyzy** [comment]
It helps reduce GPU memory usage.

**Comment by johnren-code** [comment]
So if want to get 512*512 reoslution by infer.py. Do I just need to modify face_pool from 256 to 512 ?

**Comment by jiangyzy** [comment]
Yes, but the model is trained on 256, 512 images may have some blur.

**Comment by johnren-code** [comment]
OK, Thank you for reply!
