### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by jaewoong09** [jiangyzy/GOAE#16]
Hi. Why does this error occurs?
I just followed the tutorial.

================================================== Using CUDA: 0 ==================================================
/opt/conda/envs/goae/lib/python3.8/site-packages/torch/cuda/__init__.py:145: UserWarning:
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
=> merge config from configs/swinv2.yaml
/opt/conda/envs/goae/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Encoder parmeters number is :     111218822
AFA parmeters number is :     12099904
  0%|                                                                                                                                         | 0/12 [00:00<?, ?it/s]infer.py:60: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  real_img = torch.tensor(real_img).to(device).to(torch.float32) / 127.5 - 1.
  0%|                                                                                                                                         | 0/12 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "infer.py", line 154, in <module>
    infer_main(opts, device, now)
  File "/opt/conda/envs/goae/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "infer.py", line 60, in infer_main
    real_img = torch.tensor(real_img).to(device).to(torch.float32) / 127.5 - 1.
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

**Comment by jiangyzy** [comment]
You may need to install the pytorch version compatible with your GPU version. You can also refer to [here](https://github.com/NVlabs/eg3d?tab=readme-ov-file#requirements).
