### ISSUE TITLE
MEAD dataset

### ISSUE THREAD

**Issue by johnren-code** [jiangyzy/GOAE#17]
Hello, can I ask for the MEAD dataset you use for evaluation? Including the camera poses. Thank you!

**Comment by jiangyzy** [comment]
You can download the MEAD as their official instructions, and process it to get camera pose following [this](https://github.com/jiangyzy/GOAE?tab=readme-ov-file#prepare-dataset)

**Comment by johnren-code** [comment]
Yeah, because I use the cloud server, the disk memory dont allow me to download too large dataset. And the processing time is long. So I would like to ask you for the MEAD dataset that you have previously processed for evaluation. It'll save me the time of having to deal with it myself.  😭

**Comment by jiangyzy** [comment]
Leave your email, if I can still find the files, I will send them to you.

**Comment by johnren-code** [comment]
binglinren@foxmail.com. Thank you very much !!!! It will help me a lot !!!

**Comment by johnren-code** [comment]
And It would be better If you can send me the BaiduNetdisk download link. All in all, thank you very much!

**Comment by jiangyzy** [comment]
This is a subset of MEAD that I found, you can download from [here](https://cloud.tsinghua.edu.cn/f/e7c24b41a88942f1a806/?dl=1)

**Comment by johnren-code** [comment]
Thank you very much!
