### ISSUE TITLE
The model's performence is bad

### ISSUE THREAD

**Issue by jaewoong09** [jiangyzy/GOAE#18]
![KakaoTalk_Photo_2024-04-14-16-26-16](https://github.com/jiangyzy/GOAE/assets/166790168/f7f0efb0-a3da-4788-bb25-23b48eec43c0)

The reconstructed result is blurred. I used celeba-hq 256 dataset for inference.

**Comment by jiangyzy** [comment]
Did you [preprocess](https://github.com/jiangyzy/GOAE?tab=readme-ov-file#prepare-dataset) the image before inference?

**Comment by jaewoong09** [comment]
Thank you for your response. How can i preprocess?

**Comment by jiangyzy** [comment]
You can refer to both two methods mentioned at [here](https://github.com/jiangyzy/GOAE?tab=readme-ov-file#prepare-dataset).
