### ISSUE TITLE
Evaluation Protocol

### ISSUE THREAD

**Issue by mcbuehler** [jiangyzy/GOAE#4]
Congratulations on your ICCV paper! I have some questions about the evaluation protocol.

1. FID Computation
The paper reads "_We calculate the mean square error (MSE), LPIPS [53], and FID [17] between the source image and its inversion._" (Sec. 5.2).
Could you specify how many images were used to compute FID for both the reconstruction and the novel views? Ideally, please specify which target images from MEAD were used, which view angles were synthesized, and which images were used for computing the FID statistics.

2. Identity Similarity
The paper reads 
"_We adopt a pre-trained face key point detector parsenet [55] to calculate the identity similarity._" (Sec. 5.2)
Could you describe in more detail how the identity similarity was computed? How did you handle failure cases where the pre-trained key point detector didn't output meaningful results?

Thank you!

**Comment by jiangyzy** [comment]
Thank you for your comments.
1. We mentioned the these test setting in supplementary, please refer to the [paper](https://arxiv.org/abs/2303.12326)
2. The ID computing is as [e4e](https://github.com/omertov/encoder4editing/blob/main/criteria/id_loss.py)

Hope these will help.

**Comment by mcbuehler** [comment]
Thanks, this helps. I have one more question.

The supplementary reads: 
"_Specifically, we use five views (...) images of 43 persons per frame. We randomly sample 5 frames for each person_."

Does this mean 43 people * 5 frames * 5 views = 1075 samples in total?

**Comment by jiangyzy** [comment]
Yes, you are right.
