### ISSUE TITLE
Editing directions for cats

### ISSUE THREAD

**Issue by mcbuehler** [jiangyzy/GOAE#7]
Thanks for providing editing directions for faces in `example/ws_edit`.

Could you please also provide the edit directions used for cats (﻿Fig. 1 in the [paper](https://arxiv.org/pdf/2303.12326.pdf))?

Thank you.

**Comment by jiangyzy** [comment]
The  edit directions used for cats have been update to [here](https://github.com/jiangyzy/GOAE/tree/main/example/ws_edit)

**Comment by mcbuehler** [comment]
Thanks!

**Comment by Twizwei** [comment]
How can I use them by the way? It looks like these are Bytes not `np.array`.

**Comment by Twizwei** [comment]
NVM, `array = np.frombuffer(data['archive/data/0'], dtype=np.float32).reshape(1, 14, 512)` works.
