### ISSUE TITLE
What's the difference of the camera poses between the cameras.json and label.json?

### ISSUE THREAD

**Issue by LPHFAQ** [jiangyzy/GOAE#9]
Hi, I succeeded preparing dataset using this repo: https://github.com/FeiiYin/SPI/blob/main/preprocess/ . But when using my own face img as the input of goae, I found the camera poses in cameras.json were different from those in label.json (the data in label.json seemed to be camera poses). So what's the difference of the camera poses between these two files? Can these poses of the same img in these two files be the same value?
![image](https://github.com/jiangyzy/GOAE/assets/57347617/f5563e74-dcd2-49cf-82d7-a4c6960ce707)
![image](https://github.com/jiangyzy/GOAE/assets/57347617/c5ba89e5-791a-4d86-9dc4-030f025af2d7)

**Comment by jiangyzy** [comment]
The difference iswhether the translation vector is normlized to 2.7. You can see the code [here](https://github.com/FeiiYin/SPI/blob/main/preprocess/process_camera.py#L35), and use the normalized vector as model input pose.

**Comment by LPHFAQ** [comment]
你好，你发送的邮件我已受到，我会尽快回复。

**Comment by LPHFAQ** [comment]
> The difference iswhether the translation vector is normlized to 2.7. You can see the code [here](https://github.com/FeiiYin/SPI/blob/main/preprocess/process_camera.py#L35), and use the normalized vector as model input pose.

Done, thx for your reply!
